[workspace]

members = [
    "devconsole_server",
    "devconsole_client",
    "devconsole_protocol",
    "devconsole_data_logger",

    "devconsole_serial_monitor",
    "devconsole_serial_protocol",
    "devconsole_serial_logger",
]
