[workspace]

members = [
    "devconsole-server",
    "devconsole-client",
    "devconsole-protocol",
    "devconsole-data-logger",

    "devconsole-serial-monitor",
    "devconsole-serial-protocol",
    "devconsole_serial_logger",
]
